bass-music/config/routes.rb
Rails.application.routes.draw do
  get '/albums' => 'albums#index'
  get '/albums/:id' => 'albums#show', as: :destination

end

bass-music/app/models/album.rb
class Album < ActiveRecord::Base
has_many :track
end

bass-music/app/models/track.rb
class Track < ActiveRecord::Base
belongs_to :album
end

bass-music/app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  	def index
		@albums = Album.all
	end
  	def show
    @album = Album.find(params[:id])
     @tracks=@album.track
  end
end

bass-music/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

bass-music/app/helpers/albums_helper.rb
module AlbumsHelper
end

bass-music/app/helpers/application_helper.rb
module ApplicationHelper
end

bass-music/app/views/albums/index.html.erb
<div class="row">
 <div class="col-md-3">
       	<% @albums.each do |t| %>
      <div class="thumbnail">
     
        
       
        <div class="caption">
             <div class="imageclass">
          <%= link_to (image_tag (t.cover)), destination_path(t) %>  
        </div>
          <h3 class="title"><%= t.title %>  </h3>
          <p class="artist"><%= t.artist %>  </p>
         
        </div>
      </div>
    <% end %>
  </div>
  
  
</div>

bass-music/app/views/albums/show.html.erb
<div class="show row">
  <div class="cover col-md-4">  
    <%=image_tag @album.cover %>  </div>

  <div class="col-sm-8">
    <p class="album-title"><%=@album.title %>   </p>
    <p class="album-artist"><%=@album.artist %>    </p>
    
 
    <% @tracks.each do |d| %>
    <div class="track row">
      <div class="name col-md-8"><p><%= d.name %></p></div>
      <div class="minutes col-md-4"><p><%= d.minutes %>  min</p></div>
    </div>
       <% end %>
    
    
  </div>
</div>

bass-music/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BassMusic</title>
 


    <link rel="stylesheet" href="http://s3.amazonaws.com/codecademy-content/projects/bootstrap.min.css">
    <link href='http://fonts.googleapis.com/css?family=Roboto:100,300,400,700,500' rel='stylesheet' type='text/css'>
   <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="header">
      <div class="container">
        <img class="logo" src="http://s3.amazonaws.com/codecademy-content/projects/3/bass-music/logo.svg"/>
      </div>
    </div>

    <div class="main">
      <div class="container">

        <%= yield %>
      
      </div>
    </div>


  </body>
</html>